repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.4" 
    hooks:
      - id: ruff
        language: python
        language_version: python3.12
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language: python
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        language: python
        language_version: python3.12
